/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class HtmlElement {
  constructor()
  innerText(): string
  select(selector: string): Array<HtmlElement>
  innerHtml(): string
  html(): string
}
export class HtmlDocument {
  constructor(str: string)
  select(selector: string): Array<HtmlElement>
}
